vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /avatars
            upload_destination: '%kernel.project_dir%/public/avatars'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\UniqidNamer